# Project Chimera - CodeRabbit AI Code Review Configuration
# Focus: Spec alignment, security, and architectural compliance

language: en-US
early_access: false
reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: true
  tools:
    shellcheck:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    languagetool:
      enabled: true
      level: picky
    hadolint:
      enabled: true
    
chat:
  auto_reply: true
# CRITICAL: Spec-Driven Development Checks
checks:
  # 1. SPEC ALIGNMENT (HIGHEST PRIORITY)
  - name: "Spec Alignment"
    description: "Verify code implements documented specifications"
    severity: error
    rules:
      - pattern: "src/chimera/**/*.py"
        must_contain: "# Implements: US-"
        message: "Chimera source files should reference the related spec. Include '# Implements: US-XXX' comment"

      - pattern: "tests/**/*.py"
        must_contain: "US-"
        message: "Tests must reference user story acceptance criteria"
  
  # 2. ARCHITECTURAL RULES
  - name: "No Direct API Calls"
    description: "All external integrations must use MCP abstraction"
    severity: error
    rules:
      - pattern: "src/chimera/**/*.py"
        forbidden_imports:
          - "tweepy"
          - "requests"
          - "httpx"
        message: "Use MCP abstraction. See .cursor/rules Rule 1"
        exceptions:
          - "src/chimera/mcp_servers/**"
  
  - name: "No Blocking Operations in Workers"
    description: "Workers must use async/await patterns"
    severity: error
    rules:
      - pattern: "src/chimera/services/worker/**/*.py"
        forbidden_patterns:
          - "time.sleep"
          - "requests.get"
          - "open\\(.*\\).read\\(\\)"
        message: "Use async patterns. See .cursor/rules Rule 2"
  
  - name: "OCC Required for State Updates"
    description: "State changes must use Optimistic Concurrency Control"
    severity: error
    rules:
      - pattern: "src/**/*.py"
        if_contains: "global_state.update"
        must_also_contain: "version_check"
        message: "Use OCC pattern. See specs/technical.md OCC section"
  
  - name: "Persona Validation Required"
    description: "Content generation must validate against SOUL.md"
    severity: error
    rules:
      - pattern: "src/chimera/skills/**/*.py"
        if_contains: "llm.generate"
        must_also_contain: "persona"
        message: "Include persona context. See .cursor/rules Rule 4"
  
  - name: "Budget Checks Before Transactions"
    description: "Financial operations must have CFO Judge approval"
    severity: error
    rules:
      - pattern: "src/**/*.py"
        if_contains: "wallet.send"
        must_also_contain: "cfo_judge"
        message: "Budget governance required. See .cursor/rules Rule 5"
  
  # 3. CODE QUALITY
  - name: "Type Hints Required"
    description: "All functions must have type annotations"
    severity: warning
    rules:
      - pattern: "src/**/*.py"
        must_match: "^(async )?def \\w+\\([^)]*\\) -> \\w+:"
        message: "Add type hints to all functions"
  
  - name: "Docstrings Required"
    description: "Public functions need docstrings"
    severity: warning
    rules:
      - pattern: "src/**/*.py"
        if_pattern: "^def [^_]"
        must_have_docstring: true
        message: "Add Google-style docstring"
  
  - name: "Error Handling Required"
    description: "Risky operations must have try/except"
    severity: error
    rules:
      - pattern: "src/**/*.py"
        if_contains: 
          - "await mcp_client.call"
          - "await db."
          - "await wallet."
        must_be_in: "try:"
        message: "Add error handling for external calls"
  
  # 4. TESTING
  - name: "Tests Required for Features"
    description: "New features must have corresponding tests"
    severity: error
    rules:
      - if_modified: "src/chimera/**/*.py"
        must_also_modify: "tests/**/*test_*.py"
        message: "Add tests for new code (TDD)"
  
  - name: "Test Isolation"
    description: "Tests must not depend on external services"
    severity: warning
    rules:
      - pattern: "tests/unit/**/*.py"
        forbidden_imports:
          - "anthropic"
          - "openai"
          - "google.generativeai"
        message: "Mock external services in unit tests"
  
  # 5. SECURITY
  - name: "No Hardcoded Secrets"
    description: "Credentials must come from environment"
    severity: error
    rules:
      - pattern: "**/*.py"
        forbidden_patterns:
          - 'API_KEY = "[^"]+"'
          - 'PASSWORD = "[^"]+"'
          - 'sk-ant-'
          - 'sk-proj-'
        message: "Use environment variables for secrets"
  
  - name: "SQL Injection Prevention"
    description: "Use parameterized queries"
    severity: error
    rules:
      - pattern: "src/**/*.py"
        if_contains: "execute("
        forbidden_patterns:
          - 'f"SELECT'
          - 'f"INSERT'
          - '+ "WHERE'
        message: "Use SQLAlchemy ORM or parameterized queries"
  
  # 6. TRACEABILITY
  - name: "Commit Message Format"
    description: "Commits must reference specs or issues"
    severity: warning
    rules:
      - commit_message:
        must_match: "^(feat|fix|docs|style|refactor|test|chore)\\(\\w+\\):"
        must_contain: "Refs: #\\d+|US-\\d+"
        message: "Use conventional commits + reference issue/spec"

# Learning mode (CodeRabbit learns from accepted reviews)
learning:
  enabled: true
  feedback_weight: 0.8
  
# Behavior flags
flags:
  enforce_conventional_commits: true
  enforce_linear_history: false
  require_issue_reference: true
  block_force_push: true
  require_signed_commits: false